version: "3"

services:
  reverse_proxy:
    image: nginx:latest
    container_name: reverse_proxy
    hostname: reverse_proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - sonarqube
    volumes:
      - ./config/sq-proxy.conf:/etc/nginx/conf.d/sq-proxy.conf
      - ./certs:/etc/pki/tls/sonar
    networks:
      - sonar-network


  sonarqube:
    image: karimfadl/sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    restart: always
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - sonar-network


  db:
    image: postgres:15
    container_name: db
    hostname: db
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonar-network


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:


networks:
  sonar-network:
    driver: bridge
